### ISSUE TITLE
Alignment of reverse complement of short reads to graph fails

### ISSUE THREAD

**Issue by phiweger** [ratschlab/metagraph#354]
I built a pangenome graph from a couple of bacterial genomes and now try to align some reads (Illumina) to it. This works, unless I try to get `metagraph` to align the reverse complement of the reads, too, using `--fwd-and-reverse`. Then I see the following error message:

```
docker run --entrypoint metagraph_DNA --cpus 8 -v $PWD:/data ratschlab/metagraph:latest align --fwd-and-reverse -p 8 -o /data/aln -i /data/graph.dbg /data/SRR14373579/SRR14373579_1.fastq.gz
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 141) >= this->size() (which is 141)
```

The same happens when the query is a genome, instead of reads.

Any idea if this is a bug or am I using `metagraph` incorrectly?

Thanks!

**Comment by hmusta** [comment]
Thanks for reporting this! I have a few questions which can help me reproduce this
1) Which commit are you currently using?
2) Would it be possible to share the graph you are using, or to provide a minimum working example?

**Comment by hmusta** [comment]
Also, as of commit 791952324611c54d9ac7dbb7a7dea34f9ac15521, metagraph will report the best among the alignments of the forward and reverse complement of a read by default. I am not sure if this is what you are looking for, or if you explicitly want a separate alignment to be reported for each orientation.

**Comment by phiweger** [comment]
I am using the "latest" tag from the metagraph repo -- is this current? `ratschlab/metagraph:latest`

Please find the graph I used, its annotation, the reads (`SRR...`) and genomes (`faecalis.zip`) here: [osf.io/v986u/](https://osf.io/v986u/)

**Comment by phiweger** [comment]
> I am not sure if this is what you are looking for, or if you explicitly want a separate alignment to be reported for each orientation.

No I really only want to know about the read presence/ absence when mapping to the graph or where they map to specifically. I do not want an orientation-specific report.

If this is in the commit you mention @hmusta , is there a current docker container which includes it?

**Comment by hmusta** [comment]
The release you're using should be fine. After looking into it, it turns out that this is a bug triggered by the `--fwd-and-reverse` flag which is also present in this release. I'm working on a quick fix now, but since you don't need an orientation-specific report, you can omit this flag.

As I mentioned, by default, metagraph will align the forward and reverse complement of an input read and report the best alignment among them.

**Comment by hmusta** [comment]
The wording for this flag's description in the help menu is a bit confusing, so I'll also revise that in the fix.

**Comment by phiweger** [comment]
Awesome, so just to be sure: All the flag does is change the reporting, not how the graph is queried?

**Comment by hmusta** [comment]
It's a little bit more complicated, in fact.

Given a query sequence, seeds are generated for both the query and its reverse complement and these are used to decide which of the two orientations to align (either the best one or both if they are close).

Since this is a heuristic, this may not lead to the optimal alignment being reported, so this flag exists to align the forward and reverse complement of a read fully independently in case one wants to explore this case further.

**Comment by karasikov** [comment]
So, I guess, in principle, it can lead to different results, that is, "align with --fwd-and-reverse -> select best" != "align without --fwd-and-reverse"), but this effect is the same as if you changed some other cutoff parameters controlling how much of the graph you explore in the alignment, right?

**Comment by phiweger** [comment]
> cutoff parameters are set to high enough values to find the best alignment

@karasikov is there something like "return only the best mapping". `--align-alternative-alignments` defaults to 1, is this equivalent?

**Comment by hmusta** [comment]
> > cutoff parameters are set to high enough values to find the best alignment
> 
> @karasikov is there something like "return only the best mapping". `--align-alternative-alignments` defaults to 1, is this equivalent?

Yes, this means that it returns the single best alignment (it could find) for a query.
