### ISSUE TITLE
Extract gfa file and unitig labels

### ISSUE THREAD

**Issue by phiweger** [ratschlab/metagraph#371]
Is it possible to get (1) the gfa-formatted graph and (2) the presence-absence information on which unitig carries which labels without any query? I would like to do some "network analysis" on a pangenome graph, so this would be very helpful.

**Comment by karasikov** [comment]
Hi Adrian,

Does this have to be one gfa-graph with labeled unitigs or having multiple gfa-graphs (one for each label) would work too?

**Comment by phiweger** [comment]
I would need one gfa file bc/ I want to separate "regions" in the graph based on label patterns.

**Comment by karasikov** [comment]
There is only very basic support for GFA right now.
In principle, this is easily solvable. We just need to map node ids from `path` to labels during the [extraction of unitigs](https://github.com/ratschlab/metagraph/blob/master/metagraph/src/cli/assemble.cpp#L219-L242)  (which would require loading the annotator along with the graph) and print those annotation labels extracted per unitig to GFA.
Could you describe your workflow briefly? Which tool would you be using for processing this output GFA?

I can't say how much time this will take to implement, as we have a bunch of other items on the todo and we don't need GFA for anything at the moment. Though, if there will be a PR, I'll be happy to merge it :)

**Comment by phiweger** [comment]
My workflow is to parse the gfa into a graph datastructure using the `networkx` python library and then search for conserved regions, conserved meaning present in many labels, in order to use them for probe design in target capture libraries (ie lab work).

I'd write a PR, if only I knew how to read and write C++ ;)

**Comment by karasikov** [comment]
> My workflow is to parse the gfa into a graph datastructure using the networkx python library and then search for conserved regions, conserved meaning present in many labels, in order to use them for probe design in target capture libraries (ie lab work).

Hm, interesting... Would it be reasonable to do this analysis on k-mers instead of unitigs?
We've just pushed another patch that lets you aggregate columns and compute how many labels contain each k-mer. So, this analysis can now be performed entirely within metagraph.

So you could do something like this:
```
# 1. aggregate columns (compute k-mer "frequencies") and select the common ones (occurring in >= 70% of labels)
metagraph transform_anno --aggregate-columns -o common --min-fraction 0.7 annotation.column.annodbg -v

# 2. assemble contigs from a subgraph composed of those common k-mers
metagraph assemble --diff-assembly-rules rules.json graph.dbg -a common.column.annodbg -o contigs -v
```
where `rules.json` contains the following:
```
{
    "groups": [
        {   
            "experiments": [
                {   
                    "name": "assemble_contigs",
                    "in_min_fraction": 1.0,
                    "out_max_fraction": 0.1,
                    "in": ["mask"],
                    "out": []
                }   
            ]   
        }   
    ]   
}
```
(assemble contigs from a subgraph induced by that aggregated column with label "mask", constructed in step 1)

**Comment by karasikov** [comment]
For more details on operations see https://metagraph.ethz.ch/static/docs/quick_start.html#column-operations

**Comment by phiweger** [comment]
Thank you for the response! I'll see if I can reformulate my problem to use the new command. However, I doubt that this use case would work. For example: Say I want to design a probe of 100 nt which is contained in labels {A, B, C} but not {D, E}. Using the label fraction as parameter, I cannot control which labels to include/ exclude. And with the k-mers, I loose the contiguity information, not?

**Comment by karasikov** [comment]
Actually, you can construct two columns: what to include and what to exclude. Then run differential assembly with those:
```
...
                    "in": ["mask_in"],
                    "out": ["mask_out"]
...
```

Regarding the contiguity, would it actually be different from pulling unitigs? Unitigs is also nothing but a few neighboring k-mers stitched together. So in this issue is present in both approaches. But anyway, if you set k-mer size to, say, 70+, it should solve the problem as it's very unlikely that two arbitrary k-mers happen to have a large overlap by chance.

In principle, we could restrict to only indeed contiguous sequences if we use k-mer coordinates, but this part is not used in the assembly right now. Could be a cool thing for the future.

**Comment by phiweger** [comment]
Ah that is a good idea, thanks, I will try this! Closing this for now.
