### ISSUE TITLE
Annotation slow down

### ISSUE THREAD

**Issue by Glfrey** [ratschlab/metagraph#418]
Hello again!

I've noticed a major slow down in annotation speed for a graph I'm annotating and I was wondering it's to be expected or something you'd like to look at.

The speed difference can be seen in verbose mode with the following message:

`[2022-07-25 09:46:17.135] [trace] processed 80000 sequences, last was metasub_by_kmer.80000, trying to annotate as <metasub_by_kmer.80000>, 0.196139272 sec 
[2022-07-25 09:46:17.155] [trace] processed 90000 sequences, last was metasub_by_kmer.90000, trying to annotate as <metasub_by_kmer.90000>, 0.216162477 sec 
[2022-07-25 09:46:17.175] [trace] processed 100000 sequences, last was metasub_by_kmer.100000, trying to annotate as <metasub_by_kmer.100000>, 0.23553509 sec
[2022-07-25 09:46:17.194] [trace] processed 110000 sequences, last was metasub_by_kmer.110000, trying to annotate as <metasub_by_kmer.110000>, 0.25526261 sec
[2022-07-25 09:50:39.177] [trace] processed 120000 sequences, last was metasub_by_kmer.120000, trying to annotate as <metasub_by_kmer.120000>, 262.237883299 sec
[2022-07-25 09:56:10.075] [trace] processed 130000 sequences, last was metasub_by_kmer.130000, trying to annotate as <metasub_by_kmer.130000>, 593.135529608 sec`

You can see all previous sequences took less than a second but the next batch took nearly 300 seconds and the next nearly 600 seconds. Metagraph continues to slow down for every batch after. 24 hours later, the annotation is still not complete.

My command is:

`metagraph annotate -p 64 -i var_DA.dbg -o Var_DA --anno-header --coordinates -v  var_DA.fasta.gz`

var_DA.fasta.gz is 338M, uncompressed it's 1.3Gb and contains a total of 4373290 sequences.  var_DA.dbg is 615M.

**Comment by karasikov** [comment]
Hi Gillian,

The annotation algorithm first accumulates a batch of sequences and then starts annotating them in worker threads -- that's why you see the first files are processed very quickly (it essentially just reads data), but then it starts the actual annotation process.
In short: what you observe is normal. The actual annotation speed is what you see in the last lines.

Regarding the annotation itself, I noticed that you pass `--anno-header` and `--coordinates`, which means it will create a new annotation column for each distinct header in the input file. For example, in case of reads, it would be much more efficient to put everything in a single column with coordinates, that is, `--anno-label <name> --coordinates`. Then, even though you didn't include sequence headers as annotation labels, you can still identify which read a k-mer comes from based on its coordinate in the file.
For example, say, the read length is 100 and k=31, then coordinate 304 would belong to read 4 (`floor(304/(100-31+1))`), k-mer 24 (`304-4*(100-31+1)`). That is, you can always figure out the sequence id from a coordinate even if everything is indexed in a single column. On the other hand, having fewer (in this case just 1) annotation columns reduces the space overhead and makes the annotation faster.

This approach also works if the input file has sequences of variable length. In this case, one can precompute the offsets (mapping sequence_id -> coordinate of the first k-mer), e.g. (0: read_1, 70: read_2, 140: read_3, ...) to quickly identify the sequence id from a k-mer coordinate with binary search on this array of offsets.

**Comment by Glfrey** [comment]
Hi @karasikov thank you as always. 

As for your suggestion with the annotations I should probably explain my experimental set up. I'm not actually working with reads at this point, I'm working with unitigs from the differential assembly algorithm so there's far fewer sequences to annotate. That being said there's still loads of them so perhaps your annotation suggestion is wiser than the approach I'm taking, I'd just have to write a function to determine the identity of the fragment using the coordinate reported and known length of proceeding sequences. It's certainly possible and actually something I planned on doing until I remembered I could annotate by header. I'll try both ways out and see which is better for my application.

Thank you!

**Comment by karasikov** [comment]
The slowdown should be fixed now. Please update MetaGraph to 0.3.6 (https://github.com/ratschlab/metagraph/releases/tag/v0.3.6)
