### ISSUE TITLE
lsof command not found

### ISSUE THREAD

**Issue by simone-pignotti** [ratschlab/metagraph#441]
Hi,

Thanks for developing and maintaining this incredible tool!

I encountered this error message when running `build` on an Amazon Linux 2 AWS EC2 instance, with metagraph installed in a dedicated conda environment:
```
sh: lsof: command not found
```
Here is the command I used and the relevant part of the log:
```
$ metagraph build -k 20 --min-count 3 --mode canonical --mem-cap-gb 740 --disk-swap . -p 96 -o metagraph --verbose ~/reads/*.fastq.gz 2>&1 | tee 20230310.log
[...]
[2023-03-10 14:11:21.670] [trace] Reconstructing all required dummy source k-mers...
sh: lsof: command not found
[2023-03-10 14:15:32.033] [trace] Splitting k-mers from chunk ./temp_kmers_KaNWiA/chunk_0 into 16 chunks...
[...]
```

The process continued just fine, but I don't know if this had an impact on the performances or, worse, the correctness of the results.

I have now installed the [lsof package](https://anaconda.org/conda-forge/lsof) from conda in the metagraph environment, and I recommend adding that to the conda dependencies of the next release.

Thanks again
Simone

**Comment by simone-pignotti** [comment]
PS I see you were discussing the general approach of calling `lsof` externally [here](https://github.com/ratschlab/metagraph/pull/411/files#diff-1c9b99e3cfdd8909160ac88f91e4f0d949365d3982537cbbe2afa83bb2b1f025R126), in case that helps.

**Comment by karasikov** [comment]
Hi,

It couldn't find `lsof` and hence could not compute the number of open file descriptors. This is needed to avoid opening more files than it is allowed by the system. However, since it finished successfully, apparently, it did not exceed the limit (otherwise the process would have crashed) and completed fine (no effect on performance and the result is correct).

I nevertheless suggest installing `lsof` in the future to avoid possible issues. They will never happen if the buffer is sufficiently large (like 740 GB in your case), hence, fewer files are needed, or if the limit on the number of open file descriptors is high enough in the system. However, having `lsof` installed makes this more reliable even in extreme cases.

**Comment by simone-pignotti** [comment]
Thank you!
