### ISSUE TITLE
How to solve [error] Count vectors have different size?

### ISSUE THREAD

**Issue by MitraDarja** [ratschlab/metagraph#466]
Hi,

I am sorry, but I have another question. I am trying to create a counting dbg for multiple files and tried to do that now in multiple ways and so far nothing worked. At the moment, I get the following error: "[error] Count vectors have different size".

These are the commands I used:

```
metagraph build --parallel 4 -k 21 --count-kmers --count-width 32 --outfile-base graph [input_kmcfile_1]  [input_kmcfile_2]  [input_kmcfile_3]
metagraph clean -p 16 --separately --to-fasta --primary-kmers --smoothing-window 1 -o clean graph.dbg --count-kmers --count-width 32 --smoothing-window 1
metagraph annotate --separately -p 8 -i graph.dbg --anno-filename --count-kmers --count-width 32 -o clean_anno clean.fasta.gz
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 0 --mem-cap-gb 500 -o rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/clean.fasta.gz.column.annodbg
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 1 --mem-cap-gb 500 -o rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/clean.fasta.gz.column.annodbg
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 2 --mem-cap-gb 500 -o rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/clean.fasta.gz.column.annodbg
```

The error occurs at the last command. I based the commands for the transform anno on the script [here](https://github.com/ratschlab/counting_dbg/blob/master/scripts.md), but my building is a bit different to the steps described there as far as I understand it - does that make a difference?

Any help would be greatly appreciated again.

**Comment by MitraDarja** [comment]
Hi,

thanks for your fast response. Creating individual directories solved that problem. :D 
But now I am stuck at the querying step.
For one of my sequencing files, I get the following result:

```
0	SeqA <first.fasta.gz>:1=34:2-3=37:4-5=36:6=149:7=99:8=100:9=167:10-519=255
```

What I would have expected is a result for each of my three input files. 

I used the following commands:

```
metagraph build --parallel 4 -k 21 --count-kmers --count-width 32 --outfile-base graph [input_kmcfile_1]  [input_kmcfile_2]  [input_kmcfile_3]
metagraph clean -p 16 --separately --to-fasta --primary-kmers --smoothing-window 1 -o clean graph.dbg --count-kmers --count-width 32 --smoothing-window 1
metagraph annotate --separately -p 8 -i graph.dbg --anno-filename --count-kmers --count-width 32 -o clean_anno clean.fasta.gz
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 0 --mem-cap-gb 500 -o rd0/rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/clean.fasta.gz.column.annodbg
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 1 --mem-cap-gb 500 -o rd1/rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/clean.fasta.gz.column.annodbg
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 2 --mem-cap-gb 500 -o rd2/rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/clean.fasta.gz.column.annodbg
metagraph transform_anno --anno-type row_diff_int_brwt --greedy --fast --subsample 1000000 -i first.dbg -o annotation_final rd2/clean_first.fasta.gz.column.annodbg -p 72 --parallel-nodes 10
metagraph relax_brwt -v --relax-arity 32 -p 72 -o annotation_final_relaxed annotation_final.row_diff_int_brwt.annodbg
metagraph query --query-counts -i first.dbg -a annotation_final_relaxed.row_diff_int_brwt.annodbg seqA.fa
```

I am sorry to have to bother you so much about this.

**Comment by karasikov** [comment]
Ah, I see. In the first step, you constructed a single de Bruijn graph from all three files. That's why eventually you get a single column.

To solve this, do 3 build, 3 clean, and then as you were doing.

That is:

metagraph build -p 4 -k 21 --count-kmers --count-width 32 --outfile-base graph_1 [input_kmcfile_1]
metagraph build -p 4 -k 21 --count-kmers --count-width 32 --outfile-base graph_2 [input_kmcfile_2]
metagraph build -p 4 -k 21 --count-kmers --count-width 32 --outfile-base graph_3 [input_kmcfile_3]
metagraph clean -p 16 --to-fasta --primary-kmers --smoothing-window 1 -o clean_1 graph_1.dbg --count-kmers --count-width 32 --smoothing-window 1
metagraph clean -p 16 --to-fasta --primary-kmers --smoothing-window 1 -o clean_2 graph_2.dbg --count-kmers --count-width 32 --smoothing-window 1
metagraph clean -p 16 --to-fasta --primary-kmers --smoothing-window 1 -o clean_3 graph_3.dbg --count-kmers --count-width 32 --smoothing-window 1
metagraph annotate --separately -p 8 -i graph.dbg --anno-filename --count-kmers --count-width 32 -o clean_anno clean_1.fasta.gz clean_2.fasta.gz clean_3.fasta.gz
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 0 --mem-cap-gb 500 -o rd0/rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/*.column.annodbg
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 1 --mem-cap-gb 500 -o rd1/rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/*.column.annodbg
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 2 --mem-cap-gb 500 -o rd2/rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/*.column.annodbg
metagraph transform_anno --anno-type row_diff_int_brwt --greedy --fast --subsample 1000000 -i first.dbg -o annotation_final rd2/*.column.annodbg -p 72 --parallel-nodes 10
metagraph relax_brwt -v --relax-arity 32 -p 72 -o annotation_final_relaxed annotation_final.row_diff_int_brwt.annodbg
metagraph query --query-counts -i first.dbg -a annotation_final_relaxed.row_diff_int_brwt.annodbg seqA.fa

Just remember to clean up the directories before you run this :)

**Comment by MitraDarja** [comment]
Thanks for the answer and I am really sorry, but it is still not working.
Currently, this step:
```
metagraph transform_anno -v --anno-type row_diff --count-kmers --row-diff-stage 1 --mem-cap-gb 500 -o rd1/rd -i graph.dbg -p 72 --disk-swap /scratch/local2/ clean_anno/*.column.annodbg
```

remains forever in 
```
[2023-08-02 09:14:57.254] [info] The name of the row count vector was automatically derived from the first column in batch and set to "metagraph_single/rd1/clean_anno.row_reduction"
[2023-08-02 09:14:57.254] [trace] Annotations in batch: 1
[2023-08-02 09:14:57.257] [trace] Loading annotations from file metagraph_single/clean_anno.column.annodbg
[2023-08-02 09:14:57.707] [trace] Column: metagraph_single/clean_first.fasta.gz, Density: 0.4315613699519883, Set bits: 3026319168
[2023-08-02 09:14:57.707] [trace] Annotation loading finished (1 columns)
[2023-08-02 09:14:57.707] [trace] Done loading 1 annotations
[2023-08-02 09:14:58.737] [trace] Done loading column values
[2023-08-02 09:14:58.737] [trace] Registered temporary directory /scratch/local2/temp_col_TEU8C0
[2023-08-02 09:14:58.737] [trace] Registered temporary directory /scratch/local2/temp_col_TEU8C0/0/col_0_0/temp_sorted_vector_4MJ6ML
[2023-08-02 09:14:58.737] [trace] Row reduction vector: metagraph_single/rd1/clean_anno.row_reduction
[2023-08-02 09:14:58.739] [trace] Initialized new row reduction vector
 Compute diffs        [=======================================                         ]  61.7%, 4328521728/7012488556 
```

I waited for 24 hours, if the percentage would change but nothing. I also deleted everything in the output directory and tried it again and it stopped at the same time. I have 1 TB of RAM on my machine and 15 TB in my `--disk-swap` directory, so I can not imagine that the machine is not powerful enough.

`--row-diff-stage 0` run without a problem.

**Comment by karasikov** [comment]
Hi,

This is weird, and it is hard to say what may be wrong because I've never observed any issues like this.

The script looks good, the log also looks regular.
Does it always get stuck at 61.7% or it still makes progress but very slowly?

Since you have enough RAM, can you try with `--disk-swap ""` instead of `--disk-swap /scratch/local2/` to convert it in RAM?

**Comment by MitraDarja** [comment]
Hi,

it always stops at 61.7%. I tried `--disk-swap ""` now as well and after quickly getting to 61.7%, it remains there now for ten minutes.

Is there a possibility to continue without that step?

**Comment by karasikov** [comment]
Hi, this is strange strange. Can I download that file somewhere to try it myself?

**Comment by MitraDarja** [comment]
Hi,

you can download the dbg and the columndbg from here: https://ftp.imp.fu-berlin.de/pub/darvish/

**Comment by karasikov** [comment]
I'm trying to download but it says `You don't have permission to access this resource.`

**Comment by MitraDarja** [comment]
Yeah, I forgot to change the permission, it should work now.:)

**Comment by karasikov** [comment]
Hi, I just quickly checked the stats and see that the column has a different size than the graph.

It seems like this column was constructed for a different graph.

```
$ ./metagraph stats ~/Downloads/graph.dbg 
[2023-08-04 13:13:53.254] [info] Statistics for graph '/Users/mike/Downloads/graph.dbg'
====================== GRAPH STATS =====================
k: 21
nodes (k): 4360980475
mode: basic
========================================================
====================== BOSS STATS ======================
k: 21
nodes (k-1): 4020330658
edges ( k ): 4360980475
state: stat
W stats: {'$': 61005780, 'A': 1142883240, 'C': 1033079079, 'G': 968545228, 'T': 1155467148}
F stats: {'$': 5, 'A': 1149158985, 'C': 1052826594, 'G': 989041502, 'T': 1169953389}
indexed suffix length: 12
========================================================
```
```
$ ./metagraph stats -a ~/Downloads/clean_anno.column.annodbg 
[2023-08-04 13:14:33.628] [info] Statistics for annotation '/Users/mike/Downloads/clean_anno.column.annodbg'
=================== ANNOTATION STATS ===================
labels:  1
objects: 7012488556
density: 0.431561
representation: column
========================================================
```


see that
```
nodes (k): 4360980475
```
and 
```
objects: 7012488556
```

Can you double-check the commands you ran to construct these?

__
I'll also add a check so it reports an error message right away for incompatible graph and annotation without attempting the conversion.

**Comment by MitraDarja** [comment]
Hi again,

thanks for the tip, after cleaning the directory and rerunning all steps, I managed to construct a dbg and an annotation. However, now, I get stuck at the query step, as the result for my test sequence is empty:

```
0	seqA
```

I expected to find the sequence at least in some of my experiments and don`t know what is going wrong.

My command was:
```
metagraph query --query-counts -i graph.dbg -a annotation_final_relaxed.row_diff_int_brwt.annodbg test.fa  --discovery-fraction 0 --count-labels --fast
```

Any idea, how to troubleshoot this?
